### ISSUE TITLE
Upgrading to version 4.11+ of the cli leaves an old 4.10 bf-dialog plugin installed

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-cli#1122]
I was trying to use some of the latest `dialog:merge` features but couldn't get them to work. I checked the version of the cli I was using and it was 4.10 so I upgraded to 4.11.1.  The new features still didn't work so then I upgraded to @next which is 4.13.0-preview and they still wouldn't work.

In checking the --help text for dialog:merge I noticed that it didn't match the text from the checked in code. After a complete uninstall & reinstall didn't resolve the issue I finally worked out that there was an old bf-dialog plugin installed. Manually uninstalling the plugin resolved the issue.

![image](https://user-images.githubusercontent.com/698939/108499315-f48a5500-7262-11eb-9ddd-354df2da8f09.png)

I'm assuming this is how we originally shipped bf-dialog, as a plugin, but now that its built in we're not cleaning things up by removing the old plugin.
 
[bug]

**Comment by munozemilio** [comment]
This is the behavior by design, as per oclif doc and bf plugins:install command description: 
```
Installation of a user-installed plugin will override a core plugin.
e.g. If you have a core plugin that has a 'hello' command, installing a user-installed plugin with a 'hello' command will override the core plugin implementation. 
This is useful if a user needs to update core plugin functionality in the CLI without the need to patch and update the whole CLI.`
```

As per comments from oclif devs: "The intention of this behavior comes handy in situations like this: The Heroku CLI is an oclif CLI made up of many plugins. If we wanted to make a modification to heroku config (for example), we first clone the @heroku-cli/plugin-config repository and run heroku plugins:link to add the development version into the CLI which overrides the existing core plugin.

We might also work on a replacement command like heroku addons:create in a new plugin that defines heroku addons:create even though this is already defined by a different core plugin built into the CLI.

The loading order is core < user (plugins:install) < linked (plugins:link). In other words, a user plugin overrides a core plugin and a linked plugin overrides a user plugin. If it worked the other way (say, core before linked) it would be impossible to make modifications to an existing core plugin.

There are a few other similar situations where this behavior is ideal."

What I will do is to add a message on the cli installation to highlight the status of each installed plugin and add instructions on how to update, remove, etc.

We can also discuss if we should remove the plugin on updates and override the core but that coud lead to other conflicting scenarios.
