### ISSUE TITLE
lu parser needs to handle files over 15,000 utterances

### ISSUE THREAD

**Issue by daveta** [microsoft/botframework-cli#1223]
## Versions

What CLI version are you using: 4.13.1
What OS are you using: Windows

## Describe the bug
The lu parser is designed for LUIS which imposes a constraint on the number of utterances.  For Orchestrator, it can handle more utterances and this limitation needs to be removed.

We have a customer (ATOS) who will run into this sooner than later.

## To Reproduce
Run 
`bf luis:build --in .\lu\orch_e2e.zh-cn.lu --authoringKey ... --botName test`

```
{
    "text": "[ERROR] 18374 utterances found in application. At most 15000 is allowed.",
    "errCode": 503,
    "diagnostics": [
        {
            "Message": "18374 utterances found in application. At most 15000 is allowed.",
            "Severity": "ERROR"
        }
    ]
}
 
```
[bug]

**Comment by daveta** [comment]
Would it be possible to add the large import as a test?

**Comment by sgellock** [comment]
Shiproom - not taking this for R13.  Moved to R14

**Comment by hcyang** [comment]
This issue now depends on a successful resolution of a newly found issue: https://github.com/microsoft/botframework-cli/issues/1244.
Reduce to P1. Move it beyond R14. Bf-orchestrator-cli can consume an internal JSON input and avoid consuming LU input due to the lu-parser 15000 constraint and potential 1244 bug.
