### ISSUE TITLE
[Ludown] Translate failed due to nested entity references

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-cli#124]
## Tool
Name: Ludown
Version: 1.3.3
OS: *os version*

## Describe the bug
[Hospitality.txt](https://github.com/microsoft/botbuilder-tools/files/3553664/Hospitality.txt)
See attached. Failed to translate this by 
ludown translate -k XXX --in Hospitality.lu -t zh

The error is :
![image](https://user-images.githubusercontent.com/16643193/63907023-6d349a80-ca4c-11e9-946d-888c63a753c4.png)

Other options like parse ToLuis works well.

Expected:
Ludown translate support composite entity like: 
- stay {NumNights=three more {HotelNights=days}}
Which is generated by ludown itself.

**Comment by vishwacsena** [comment]
Sorry, I have considered adding support for composite utterance labels but every time I end up with no good way to do it since localizing things this way can be inaccurate. 

A better solution would be for LU format to support multiple instance of an utterance with non overlapping labels - this will be a good feature to add to improve readability for overlapping entity labels in general and will make things more easier to stable for localization purposes. 

Once that feature is in, localization will be supported without any issues but you will need to update the source .lu files to take advantage of that feature. So in your example, you would have 2 utterances in the .lu file instead of one - 

```markdown
- stay {NumNights=three more {HotelNights=days}}
```

With the change: 
```markdown
- stay three more days
    - stay {NumNights = three more days}
    - stay three more {HotelNights = days}
```

**Comment by vishwacsena** [comment]
This PR has the fix for what I was suggesting above. With this, you can break the source LU file into individual lines without having to worry about nested utterance definition - https://github.com/microsoft/botframework-cli/pull/148

Note: there is no guarantee that machine translation will translate all parts of a sentence correctly. So you should still review/ verify the machine translation in all cases.
