### ISSUE TITLE
Not able to install botframework-cli dependency bf-orchestratory-cli due to unsupported error.

### ISSUE THREAD

**Issue by suraj5789** [microsoft/botframework-cli#1356]
## Versions
What CLI version are you using. >> 4.15.0
What Nodejs version are you using >> 16.18.1
What command-line interpreters are you using >> Bash
What OS are you using >> MAC OS Monterey

## Describe the bug
I am not able to execute npm install -g @microsoft/botframework-cli 

Getting below error.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@microsoft/bf-orchestrator-cli@4.15.0',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.19.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @microsoft/bf-orchestrator-cli@4.15.0: wanted {"os":"darwin,linux,win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

## To Reproduce
1. Go to bash command prompt
2. execute npm install -g @microsoft/botframework-cli 
3. See error

## Expected behavior
All BotFramework CLI dependencies should have install successfully. 

[bug]

**Comment by anishprasad01** [comment]
Hi @suraj5789,

As the error message says, this error is occurring because the bf-cli is incompatible with your system architecture. I presume you are attempting to install on a Mac with Apple silicon? The M1 and M2 chips are built on the ARM architecture, which is a different CPU architecture than the x86 architecture used by the Intel Macs which preceded them. 

As you can see under `arch` the "wanted" section, it requires an x86 machine, but you have an ARM machine (see `arch` in the "current" section).
* `wanted {"os":"darwin,linux,win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})`

However, there is a workaround. Macs with Apple silicon have an emulation layer called [Rosetta 2](https://support.apple.com/en-us/HT211861) which can interpret programs written for Intel Macs and allow them to run on Apple silicon. You can make use of this to run bf-cli on an M1/M2 Mac.

Here are the steps to get bf-cli running:
1. Download and install an alternative terminal application (such as iTerm) of your choice
2. Open the Applications window in Finder, and find the terminal app you just installed
3. Open the "Get Info" menu and check the box that says "Open with Rosetta"
4. Open the new terminal and install Node v14.x
5. Run the npm command to install bf-cli

From this point on, that new terminal app will always run in emulation, and will report its architecture as x86. You can use it whenever you want to run tools that don't support Apple silicon, including bf-cli.

**Comment by suraj5789** [comment]
Thanks @anishprasad01 - It worked for me.

**Comment by adam-boosted** [comment]
The mentioned workaround doesn't work on my Apple M2 Pro

<img width="1072" alt="image" src="https://github.com/microsoft/botframework-cli/assets/122387164/a260c7d5-d1ef-4340-9967-b988c6aaa22d">
