### ISSUE TITLE
Refinement to lu/entity definition syntax

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/botframework-cli#452]
>

> ### Definition
> Entites are declarated via
> ```markdown
> @ \<entity-type> \<entity-name> [[hasRoles] \<comma-separated-list-of-roles>]
> ```

## 1. `@` 
can understand as a entity declaration operator, same as `const, var`, but it's effect not only one line, but until meet next `@` entity declaration. it's better to have a structure `end mark`, even wrap with `{ }` etc.

## 2. ` <entity-type> <entity-name> ` 
fellows the common C style PL naming routine, It's nice, easy understanding, but when I meet some code like
```
@ ml name
@ name hasRole role1
.... many line ....
.... many line ....
.... many line ....
.... many line ....
.... many line ....
@ name hasRole role2
```
when I first look at `@ name hasRole role2`, I would of course apply  the `@ <entity-type> <entity-name> ` pattern to understand. which is wrong. I have to look up `name`, find out `oh, it's an entity! not a type`. lose syntax case caused special case would increase the learning curve.

## 3.  ` <entity-type> <entity-name> [hasRoles,] role1, role2`
`hasRoles` is useless but cause more confuse, what if i named a role as `hasRoles` ?

if we remove it  ` entity-type> <entity-name> role1, role2`,
a bad example like
`@ ml name0 name1, name2`
It's very natural to split as `@ ml name0 name1 ` +  `,` + `name2`,  cause there is a `,`  the most common used splitter.

i would prefer some thing like: 
`@ml name0: name1 | name2`
`@ml name0[name1, name2]`
`@ml name0/{name1,name2}`

## 4. what is a `Role` ?

> Roles](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-roles) are named, contextual subtypes of an entity.
> 
> Every entity type except Phrase Lists can have [roles](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-roles). 
> 
> Roles give a name to those differences:
> 
> |Entity	|Role	|Purpose|
> |-------|-------|-------|
> |Location	|origin	|where the plane leaves from|
> |Location	|destination	|where the plane lands|
> 

as the document said, it's some thing like **subtypes**, why it fellow the naming pattern
` Type subType  declaration ` 
then it should be some notation like:
` <entity-type> role1, role2 <entity-name>  `
` <entity-type> [role1, role2] <entity-name>  `
` <entity-type>/{role1,role2} <entity-name>  `

## 5. List entity, Composite entity
```markdown

> @ list color favColor, screenColor
> @ color =
>     - \<normalized-value>
>         - \<synonym1>
>         - \<synonym2>
>         - ...
>     - \<normalized-value>
>         - \<synonym1>, \<synonym2>, ...
>  
> > Alternate definition
> 
> @ list color favColor, screenColor =
>     - \<normalized-value>
>         - \<synonym1>; \<synonym2>; ...
> @ composite deviceTemperature = [device, customDevice, temperature]
> 
```

the huge definition code looks like do the **declaration** and **assignment** at the same time.
and the **variable** `color` has a very complicate **type** .

**Comment by boydc2014** [comment]
Offline talked with @zhixzhan, let me summarize a little bit, actually there are two major feedback. 

1. the scope of the notion of "@".

The confusing comes from that "we allow define one entity with @, and later additively update that definition". 

This will cause the impression that "entity is not defined in one single line or one single block", which means, if i look at this specific line or text block, it don't grantee i have a full picture of this entity. Because i kind of worried, maybe somewhere else, this entity is updated again. 

For examples
```
> case 1: add roles later
@ml name
@name hasRoles role1

> case 2: `assign` values later
@ list color favColor
@ color = 
 - ... some values
```

I feel the same way, especially we don't force those lines must come together. My suggestion is we should allow or require entity is defined only once, in one line or multiple lines, the declaration and assignment should happened in same place.  We scarify some flexibility to be more readable. 

2. the syntax for roles definition

 * The use of comma is very confusing because `@type name role1, role2` don't feels role1 and role2 are together, it feels like there are two parts "type name role1" and "role2". 
 * because role is "sub-type", it feels naturally that subType should follow type, instead of "type, name, sub-type", so the proposed syntax is `@type (role1, role2) name`   or `@type[role1, role2] name`, and it also feels nature to add a "=" at the end following the name directly, instead of following the roles. 
 * if the proposed syntax is adopted, the "hasRoles" is not necessary

3.

**Comment by vishwacsena** [comment]
@boydc2014 - we can require 1) by convention but should not force that on the parser. This is required because to enable composition, definitions (in particular list definitions) could be scattered across .lu documents. 
2) I like the idea of supporting `@type (role, ...) name =` but do not have very strong feeling about how much it improves readability. For sure will keep this in the backlog unless there are pressing reasons to address these now and if so, can you clarify a bit more?

**Comment by vishwacsena** [comment]
No plans to do this.
