### ISSUE TITLE
BF luis:application commands throws access denied error

### ISSUE THREAD

**Issue by sschutten** [microsoft/botframework-cli#611]
## Versions
@microsoft/botframework-cli/4.7.0 win32-x64 node-v12.13.1

## Describe the bug
Executing the `bf luis:application` commands  always throws an access denied error.

For some reason the tool speaks of the `subscription key`, although they are now called the `authoring key` and `prediction key`. What key do I need to use?

- The authoring resource was properly assigned
- The correct endpoint url was used
- I tried to use the authoring key for the subscription key
- I tried to use a prediction key for the subscription key
- My region is westeurope

## To Reproduce
Execute the either the `bf luis:application:import` or `bf luis:application:create` commands.

## Expected behavior
I would expect the application to be created or imported successfully.

**Comment by munozemilio** [comment]
@sschutten thanks for reporting this. We will include this as part of our R8 release

**Comment by munozemilio** [comment]
The fix is addressed in our preview bits...If by any chance you want to try it you can install them by changing your registry like this:
```
npm config set registry https://botbuilder.myget.org/F/botframework-cli/npm/ 

npm i -g @microsoft/botframework-cli
```

**Comment by stephanbisser** [comment]
I have the same error with the following command:

`bf luis:application:import --endpoint "https://westeurope.api.cognitive.microsoft.com" --subscriptionKey "myAuthoringKey" --name "SolvionQnABotTemplateLUISApp" --in "C:\Users\sbi\source\repos\SolvionQnATemplate\main.json"`

**Failed to import app: Error: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.**

If I switch to the preview bits I get this error:
**Failed to import app: Error: The application ID cannot be null or empty.**

How to achieve this?

**Comment by munozemilio** [comment]
@stephanbisser Im using this [json](https://github.com/microsoft/botframework-cli/blob/master/packages/luis/test/fixtures/sample-app.json) to test and works just fine for me:

```
EMILIO-LAPTOP:luis emiliomunoz$ ./bin/run luis:application:import --subscriptionKey 800db3b9533a4eb6849d92f0fc824cdc --endpoint https://westus.api.cognitive.microsoft.com --in ./../luis/test/fixtures/sample-app.json

App successfully imported with id 6c461cfb-f8d6-4514-ab29-e95e4359f833.
```

By any chance do you see some difference?

**Comment by stephanbisser** [comment]
Hi @munozemilio thanks for the sample json. What I found is that if I do not specify the following things in my .lu file the .json won't get created accordingly:

```
> LUIS application information
> !# @app.name = SolvionQnABotTemplate
> !# @app.desc = LUIS app Solvion QnA Bot Template
> !# @app.versionId = 0.1
> !# @app.culture = de-de
> !# @app.luis_schema_version = 6.0.0
```

Is there any chance to check that when running `bf luis:convert` to see if the details like app name or version are present?

**Comment by munozemilio** [comment]
@stephanbisser  Could you please open a bug on this?
