### ISSUE TITLE
cant add new utterances to Communication.Confirm intent

### ISSUE THREAD

**Issue by ELTemi** [microsoft/botframework-cli#862]
Hello I cant add new utterances to the Communication.Confirm intent neither can i delete the intent. Also cant train the app wither possibly due to it not having any utterances. i thought that prebuilt intent will have some utterances already.

I also tried to move some utterances around intents and it wont either. Please help

**Comment by jwiley84** [comment]
@ELTemi What is Communication.Confirm? Is this from a sample?

**Comment by vishwacsena** [comment]
@ELTemi prebuilt domain intents can only be added directly via the `luis.ai` portal because they need additional intent meta-data that is only available through the portal. 

I just verified the following and they all work - 

1. Created a new app with `Communication.Confirm` prebuilt intent to my application. Exported it to .lu format. 

```markdown
> !# @intent.inherits = name : Communication.Confirm; domain_name : Communication; model_name : Confirm

## Communication.Confirm
- alright
- correct
- correct yes
- do it
- ...
```
2. Added new utterances and removed some utterances. Set the app version to 0.2 and re-imported the .lu as a new application version and it worked. 
3. I removed the `Communication.Confirm` intent as well as the associated intent meta-data comment, versioned it 0.3 and imported the .lu and it worked. 

Can you please try with above guidance and if you continue to repro the issue, please comment here with clear repro steps? Thanks.
