### ISSUE TITLE
[QnaBuild] Get QnARuntimeError(Unable to connect to Azure search service) when publishing to the qna service. 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botframework-cli#942]
Sorry, something went wrong with publishing. Try again or exit out of this task.

{ "error": { "code": "QnaRuntimeError", "message": "Runtime error.", "innerError": { "message": "Unable to connect to Azure search service. Please verify that the Azure search resource in your QnAMaker service is up and running.", "code": "AzureSearchBadState", "innerError": { "code": "Index 43456541-39c3-45b2-917e-967aca1176c8 doesn't exist" } } } }

Reproduce steps:
Create a qna bot and start. 
it only happens in specific qna service which might exceed some quota/limitation. 

[bug]

**Comment by feich-ms** [comment]
I did some investigation and the root cause is the published knowledge bases limit here https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/limits#knowledge-bases. We can give users hints if their published kbs are more than the maximum number of their pricing tier.

![image](https://user-images.githubusercontent.com/43032123/91125939-785ced80-e6d5-11ea-9fe3-ca483d874562.png)
