### ISSUE TITLE
bf luis:cross-train doesn't work with languages.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#996]
## Versions
4.10.1

## Describe the bug
when I run ```bf luis:cross-train --in . --rootDialog=my.dialog``` it fails because I don't have a my.lu file, even though I have a my.en-us.lu file.

## To Reproduce
Try to use bf luis:cross-train on a composer project

## Expected behavior
1. it should be language aware (aka, I need to be able to build targeting 1..N) languages.
2. it should not require a .lu file with no language 

The file pattern is resource.{lang}.lu so that 
* foo.en-us.lu
* foo.de-de.lu
* foo.es-es.lu 
are considered different languages for the same resource "foo".  

luis:cross-train should build models for each language that it finds, and should not be assuming that the resource name is just .lu. 

[bug]

**Comment by boydc2014** [comment]
Since cross-train is supporting Composer's scenario in which there is only <locale>.lu, so i think cross-train supports multi-languages. But Composer is calling cross-train as a lib and using a specific config. I guess there is a gap between the config composer used and the simple command line call as above, @feich-ms can you point to what kind of config should be passed in to support languages? 

@tomlm Composer will soon dump it's cross-train config, so that it can be used together with cross-train cli directly and output the exact same output as within Composer.

**Comment by feich-ms** [comment]
Hi @tomlm, currently the multi languages should be specifically set in config like below which means each language has its own mapping rules.
```json
{
    "./foo.en-us.lu": {
        "rootDialog": true,
        "triggers": {
            "bar_trigger": "./bar.en-us.lu",
        }
    },
    "./foo.de-de.lu": {
        "rootDialog": true,
        "triggers": {
            "bar_trigger": "./bar.de-de.lu",
        }
    },
    "./foo.es-es.lu": {
        "rootDialog": true,
        "triggers": {
            "bar_trigger": "./bar.es-es.lu"
        }
    }
}

**Comment by feich-ms** [comment]
Close this one first since multi languages can be supported by specifying mapping rules of different languages in config. If this is not the good direction, we can open another issue to track the refactoring.
