### ISSUE TITLE
bf luis:cross-train is expecting lu files to be in the same folder as the .dialog

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#999]
## Versions
4.10.1

## Describe the bug
bf luis:Cross-train is expecting lu files to be in the same folder as the dialog, which is not the way that composer organizes them.

## To Reproduce
Look at line 105 of confighelper.js
```javascript
 const luFilePath = dialogPath.replace('.dialog', '.lu')
```

## Expected behavior
lu files are a naming convention NOT a location convention. 

[bug]

**Comment by boydc2014** [comment]
Thanks, @tomlm,  Composer is using cross-train lib with direct lib call, instead of running command line.  As part of the Composer's effort to make sure Composer authored bot can be integrated with CI/CD environment, Composer will output the cross-train config it used, and we will make sure cli and directly consume that without issue.

**Comment by feich-ms** [comment]
Closed by #1024, there is no config discovery and --config is required in cli now.
